export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const TOGGLE_PROFILE_MODAL = "TOGGLE_PROFILE_MODAL";
export const ADD_TO_WISHLIST ="ADD_TO_WISHLIST";
export const DELETE_TO_WISHLIST = "DELETE_TO_WISHLIST";